[project]
name = "pidtune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=7.0.3",
]
[tool.ty.environment]
#extra-paths = ["/usr/lib/python3/dist-packages"] 
